Feature/1 login
Trapdafifou/seasonal pull request #5
Opened 2018-06-04 08:31 UTC by elgrim312

2018-06-04 11:48 UTC, zelazna requested changes
Quelques trucs a revoir mais cool dans l'ensemble, apres le merge je vais tester sur la nouvelle version de l'API

2018-06-04 11:48 UTC, zelazna commented on app/src/main/java/com/example/elgrim/seasonal/LoginActivity.kt
> +                            if (response.toString().isBlank()) {}
check plutot le fait que ca ne le soit pas -> !response.toString().isBlank()

2018-06-04 11:48 UTC, zelazna commented on app/src/main/java/com/example/elgrim/seasonal/LoginActivity.kt
> +                alert("Les champs email et mot de passe son obligratoire") {
obligratoire -> obligatoire :)

2018-06-04 11:48 UTC, zelazna commented on app/src/main/java/com/example/elgrim/seasonal/adapter/CandidateAdapter.kt
> +    val format = SimpleDateFormat("dd/MM/yyy")
je suis pas certain que ce format de date marche

2018-06-04 21:25 UTC, Trapdafifou reviewed
Hormis les changements demandés par constantin, RAS

2018-06-04 21:25 UTC, Trapdafifou commented on app/src/main/java/com/example/elgrim/seasonal/LoginActivity.kt
> +                alert("Les champs email et mot de passe son obligratoire") {
Il ne faut pas en plus utiliser un ```@string/``` ?

2018-06-05 05:28 UTC, zelazna commented on app/src/main/java/com/example/elgrim/seasonal/LoginActivity.kt
> +                alert("Les champs email et mot de passe son obligratoire") {
ouais ca serais mieux

2018-06-05 07:03 UTC, elgrim312 commented on app/src/main/java/com/example/elgrim/seasonal/LoginActivity.kt
> +                            if (response.toString().isBlank()) {}
bien vue

2018-06-05 07:05 UTC, elgrim312 commented on app/src/main/java/com/example/elgrim/seasonal/adapter/CandidateAdapter.kt
> +    val format = SimpleDateFormat("dd/MM/yyy")
si tkt c'est tester

2018-06-05 07:59 UTC, zelazna commented on app/src/main/java/com/example/elgrim/seasonal/CandidateList.kt
> +        val objectRequest = JsonObjectRequest(Request.Method.GET, "https://seasonal-api.herokuapp.com/api/v1/candidates", null,
a mettre dans un fichier de constantes

2018-06-05 07:59 UTC, zelazna commented on app/src/main/java/com/example/elgrim/seasonal/LoginActivity.kt
> +    val url_request = "https://seasonal-api.herokuapp.com/api/v1/rest-auth/login/"
a mettre dans un fichier de constantes

2018-06-05 08:00 UTC, zelazna commented on app/src/main/java/com/example/elgrim/seasonal/candidate/CandidateList.kt
> +        val objectRequest = JsonObjectRequest(Request.Method.GET, "https://seasonal-api.herokuapp.com/api/v1/candidates/", null,
a mettre dans un fichier de constantes

2018-06-05 08:00 UTC, zelazna commented on app/src/main/res/values/styles.xml
> +    <style name="sesonal" parent="AppTheme" >
typo sesonal -> seasonal

2018-06-06 09:03 UTC, closed without merging