Feature/2 register candidate
Trapdafifou/seasonal pull request #8
Opened 2018-06-06 12:03 UTC by Trapdafifou

2018-06-06 12:04 UTC, Trapdafifou commented
WIP this should not be Merged

2018-06-06 12:13 UTC, zelazna requested changes

2018-06-06 12:13 UTC, zelazna commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidate2Activity.kt
> +        val experienceValues: List<Number> = arrayListOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
https://kotlinlang.org/docs/reference/ranges.html

2018-06-06 12:13 UTC, zelazna commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidate2Activity.kt
> +        registerJobDateSpinner!!.text = sdf.format(calendar.getTime())
tu etait obligé de faire ca ? il est forcement defini ?

2018-06-06 12:13 UTC, zelazna commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidateActivity.kt
> +        val lastName: String? = registerEditLastName.text.toString()
check si tu peux enlever .toString()

2018-06-06 12:13 UTC, zelazna commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidateActivity.kt
> +        data = mapOf("lastName" to lastName,
return mapOf(....

2018-06-06 12:13 UTC, zelazna commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidateActivity.kt
> +                    "Veuillez remplir un email valide")
a mettre dans string/values

2018-06-06 12:13 UTC, zelazna commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidateActivity.kt
> +                        "Veuillez remplir le $key")
a mettre dans string/values

2018-06-06 12:26 UTC, elgrim312 commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidate2Activity.kt
> +        registerJobDateSpinner.text = "--/--"
fais une variable connard

2018-06-06 12:26 UTC, elgrim312 commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidate2Activity.kt
> +        val aa = ArrayAdapter(this, android.R.layout.simple_spinner_item, populate_item)
alors pour le nm de la variable va niquer ta mére

2018-06-06 13:20 UTC, Trapdafifou commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidateActivity.kt
> +        val lastName: String? = registerEditLastName.text.toString()
Je ne puis

2018-06-06 13:23 UTC, Trapdafifou commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidate2Activity.kt
> +        val experienceValues: List<Number> = arrayListOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
done

2018-06-06 13:24 UTC, Trapdafifou commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidate2Activity.kt
> +        registerJobDateSpinner!!.text = sdf.format(calendar.getTime())
done

2018-06-06 13:24 UTC, Trapdafifou commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidateActivity.kt
> +        data = mapOf("lastName" to lastName,
done

2018-06-06 13:36 UTC, Trapdafifou commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidate2Activity.kt
> +        val aa = ArrayAdapter(this, android.R.layout.simple_spinner_item, populate_item)
done

2018-06-06 13:36 UTC, Trapdafifou commented on app/src/main/java/com/example/elgrim/seasonal/RegisterCandidate2Activity.kt
> +        registerJobDateSpinner.text = "--/--"
done

2018-06-07 14:25 UTC, Trapdafifou commented
PR à jour

2018-06-07 15:00 UTC, merged